// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7RrEfY_eBaxCht_uow3ardkzIltdMUc',
    appId: '1:687474675943:web:e9dd499b94292e6da4d242',
    messagingSenderId: '687474675943',
    projectId: 'nikkiapurimarimari',
    authDomain: 'nikkiapurimarimari.firebaseapp.com',
    storageBucket: 'nikkiapurimarimari.firebasestorage.app',
    measurementId: 'G-049HXCMXPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FKesgXqi58RXnyauDiNn6ciMyfVtUDw',
    appId: '1:687474675943:android:f79a153b6b88ffd3a4d242',
    messagingSenderId: '687474675943',
    projectId: 'nikkiapurimarimari',
    storageBucket: 'nikkiapurimarimari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNdaovHEeTK-Jq2S1iORjEBbUi-yF2GQ',
    appId: '1:687474675943:ios:e2d88b4c3d0b12cca4d242',
    messagingSenderId: '687474675943',
    projectId: 'nikkiapurimarimari',
    storageBucket: 'nikkiapurimarimari.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNdaovHEeTK-Jq2S1iORjEBbUi-yF2GQ',
    appId: '1:687474675943:ios:e2d88b4c3d0b12cca4d242',
    messagingSenderId: '687474675943',
    projectId: 'nikkiapurimarimari',
    storageBucket: 'nikkiapurimarimari.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe7RrEfY_eBaxCht_uow3ardkzIltdMUc',
    appId: '1:687474675943:web:e737d5f480d29c64a4d242',
    messagingSenderId: '687474675943',
    projectId: 'nikkiapurimarimari',
    authDomain: 'nikkiapurimarimari.firebaseapp.com',
    storageBucket: 'nikkiapurimarimari.firebasestorage.app',
    measurementId: 'G-E8M8ZQ77TB',
  );

}